/**
 * Car Loader implementation for MCU
 */
#include "car_loader.h"

extern "C" {
#include "sd_loader.h"
}

#include "cJSON.h"

#include <cstdio>
#include <cstring>

namespace exhaust {

/// Temporary buffer for JSON file (on stack or static)
static char g_json_buf[4096];

/// Parse layer entries from a JSON array.
/// Returns number of layers parsed.
static uint8_t parse_layers(cJSON* arr, const char* car_dir, SdramPool& pool,
                            EngineVoice::LayerConfig* layers, uint8_t max_layers)
{
    if (!arr || !cJSON_IsArray(arr))
        return 0;

    uint8_t count = 0;
    cJSON* item = NULL;
    cJSON_ArrayForEach(item, arr)
    {
        if (count >= max_layers)
            break;

        cJSON* j_file = cJSON_GetObjectItem(item, "file");
        cJSON* j_rpm = cJSON_GetObjectItem(item, "rpm");

        if (!j_file || !j_rpm)
            continue;

        // Build full path
        char path[128];
        snprintf(path, sizeof(path), "%s/%s", car_dir, j_file->valuestring);

        // Allocate space in SDRAM and load WAV
        sd_wav_info_t wav_info;
        // First pass: get file size (peek)
        // We'll allocate generously — max 500K samples per layer (~11s at 44.1kHz)
        const uint32_t max_samples = 500000;
        int16_t* sample_buf = pool.alloc(max_samples);
        if (!sample_buf)
            break; // SDRAM full

        uint32_t loaded = sd_wav_load(path, sample_buf, max_samples, &wav_info);
        if (loaded == 0) {
            // Failed to load, reclaim space
            pool.used -= max_samples;
            continue;
        }

        // Shrink allocation to actual size
        pool.used -= (max_samples - loaded);

        // Fill layer config
        layers[count].data = sample_buf;
        layers[count].length = loaded;
        layers[count].rpm = (float)j_rpm->valuedouble;

        // Envelope and pitch will be auto-generated by set_onload_layers_auto()
        layers[count].vol_in_start = 0;
        layers[count].vol_in_end = 0;
        layers[count].vol_out_start = 0;
        layers[count].vol_out_end = 0;
        layers[count].min_pitch = 0.5f;
        layers[count].max_pitch = 2.0f;
        layers[count].pitch_start_rpm = 0;
        layers[count].pitch_end_rpm = 0;

        count++;
    }
    return count;
}

bool car_load(const char* car_dir, SdramPool& pool, LoadedCar& car)
{
    // Load car.json
    char json_path[128];
    snprintf(json_path, sizeof(json_path), "%s/car.json", car_dir);

    uint32_t json_len = sd_read_file(json_path, g_json_buf, sizeof(g_json_buf));
    if (json_len == 0)
        return false;

    cJSON* root = cJSON_Parse(g_json_buf);
    if (!root)
        return false;

    // Engine config
    cJSON* j_cyl = cJSON_GetObjectItem(root, "cylinders");
    if (j_cyl)
        car.cylinders = (uint8_t)j_cyl->valueint;

    cJSON* j_idle = cJSON_GetObjectItem(root, "rpm_idle");
    if (j_idle)
        car.rpm_idle = (float)j_idle->valuedouble;

    cJSON* j_redline = cJSON_GetObjectItem(root, "rpm_redline");
    if (j_redline)
        car.rpm_redline = (float)j_redline->valuedouble;

    cJSON* j_inertia = cJSON_GetObjectItem(root, "inertia");
    if (j_inertia)
        car.inertia = (float)j_inertia->valuedouble;

    cJSON* j_torque = cJSON_GetObjectItem(root, "peak_torque");
    if (j_torque)
        car.peak_torque = (float)j_torque->valuedouble;

    cJSON* j_torque_rpm = cJSON_GetObjectItem(root, "peak_torque_rpm");
    if (j_torque_rpm)
        car.peak_torque_rpm = (float)j_torque_rpm->valuedouble;

    // Transmission
    cJSON* j_gears = cJSON_GetObjectItem(root, "gear_ratios");
    if (j_gears && cJSON_IsArray(j_gears)) {
        car.num_gears = 0;
        cJSON* g = NULL;
        cJSON_ArrayForEach(g, j_gears)
        {
            if (car.num_gears < 8)
                car.gear_ratios[car.num_gears++] = (float)g->valuedouble;
        }
    }

    cJSON* j_final = cJSON_GetObjectItem(root, "final_drive");
    if (j_final)
        car.final_drive = (float)j_final->valuedouble;

    // Load audio layers
    cJSON* j_onload = cJSON_GetObjectItem(root, "onload");
    car.num_onload = parse_layers(j_onload, car_dir, pool, car.onload_layers, kMaxLayers);

    cJSON* j_offload = cJSON_GetObjectItem(root, "offload");
    car.num_offload = parse_layers(j_offload, car_dir, pool, car.offload_layers, kMaxLayers);

    cJSON_Delete(root);
    return (car.num_onload > 0); // At least onload layers required
}

void car_apply(const LoadedCar& car, EngineVoice& engine, Transmission& trans,
               CombustionPulse& combustion, IdleFluctuation& idle)
{
    // Configure engine voice
    engine.set_engine_config(car.cylinders, 48000);
    engine.set_onload_layers_auto(car.onload_layers, car.num_onload);
    if (car.num_offload > 0) {
        engine.set_offload_layers_auto(car.offload_layers, car.num_offload);
    }

    // Configure transmission
    Transmission::Config tc;
    tc.rpm_idle = car.rpm_idle;
    tc.rpm_redline = car.rpm_redline;
    tc.inertia = car.inertia;
    tc.peak_torque = car.peak_torque;
    tc.peak_torque_rpm = car.peak_torque_rpm;
    tc.final_drive = car.final_drive;
    tc.num_gears = car.num_gears;
    for (int i = 0; i < car.num_gears; i++)
        tc.gear_ratios[i] = car.gear_ratios[i];
    trans = Transmission(tc);

    // Configure combustion pulse
    CombustionPulse::Config pc;
    pc.cylinders = car.cylinders;
    pc.volume = 0.15f;
    pc.rpm_fade_start = car.rpm_redline * 0.4f;
    pc.rpm_fade_end = car.rpm_redline * 0.6f;
    combustion.set_config(pc);

    // Configure idle fluctuation
    IdleFluctuation::Config ic;
    ic.amplitude = 25.0f;
    ic.rate = 1.0f;
    ic.rpm_threshold = car.rpm_idle * 1.5f;
    idle.set_config(ic);
}

} // namespace exhaust
